version: '3.8'

services:
  lianjia-helper:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./data:/data/db
    restart: unless-stopped
